-- INNER JOIN
--USE SUP_2B_NOVO
USE SUPERMERCADO_2B

--EXEMPLO
SELECT COD_CLI, NUM_PED, PEDIDO.COD_PROD, NOME_PROD FROM PEDIDO INNER JOIN PRODUTO
ON PEDIDO.COD_PROD = PRODUTO.COD_PROD

-- 1) Listar os campos COD_PROD, NOME_PROD, COD_FORN da tabela PRODUTO 
--    e os campos NOME_FORN e ENDERECO da tabela FORNECEDOR.

SELECT COD_PROD, NOME_PROD, FORNECEDOR.COD_FORN, FORNECEDOR.NOME_FORN, FORNECEDOR.ENDERECO FROM PRODUTO INNER JOIN FORNECEDOR
ON PRODUTO.COD_FORN = FORNECEDOR.COD_FORN
WHERE NOME_FORN LIKE '%UNI%'


-- 2) Listar os campos COD_PROD, NOME_PROD, TIPO_EMBAL da tabela PRODUTO 
--    e os campos SIGLA_EMB e DESCRI_EMB da tabela EMBALAGEM. 

SELECT COD_PROD, NOME_PROD, EMBALAGEM.TIPO_EMBAL, EMBALAGEM.SIGLA_EMB, EMBALAGEM.DESCRI_EMB FROM PRODUTO INNER JOIN EMBALAGEM
ON PRODUTO.TIPO_EMBAL = EMBALAGEM.TIPO_EMBAL


-- 3) Listar Número do Pedido, Nome do cliente, Código do produto e Nome do produto. 

SELECT NUM_PED, CLIENTE.NOME_CLI, PRODUTO.COD_PROD, PRODUTO.NOME_PROD FROM PEDIDO INNER JOIN PRODUTO
ON PEDIDO.COD_PROD = PRODUTO.COD_PROD INNER JOIN CLIENTE
ON PEDIDO.COD_CLI = CLIENTE.COD_CLI

-- 4) Listar Número do Pedido, Nome do cliente, Código do produto e Nome 
--    do produto para os pedidos com valor total maior que R$10.00

SELECT NUM_PED, VLOR_TOT, CLIENTE.NOME_CLI, PRODUTO.COD_PROD, PRODUTO.NOME_PROD FROM PEDIDO INNER JOIN PRODUTO
ON PEDIDO.COD_PROD = PRODUTO.COD_PROD INNER JOIN CLIENTE
ON PEDIDO.COD_CLI = CLIENTE.COD_CLI
WHERE VLOR_TOT > 10



-- 5) Listar código do produto, nome do produto, codigo do fornecedor e nome 
--    do fornecedor quando o nome do fornecedor começar com JOHNSON.

SELECT COD_PROD, NOME_PROD, FORNECEDOR.COD_FORN, FORNECEDOR.NOME_FORN FROM PRODUTO INNER JOIN FORNECEDOR
ON PRODUTO.COD_FORN = FORNECEDOR.COD_FORN
WHERE NOME_FORN LIKE 'JOHNSON%'


-- 6) Listar quantos pedidos existem para cada cliente cujo nome começa com a letra J.

SELECT NUM_PED, QTD_PROD, VLOR_TOT, CLIENTE.NOME_CLI FROM PEDIDO INNER JOIN CLIENTE
ON PEDIDO.COD_CLI = CLIENTE.COD_CLI
WHERE NOME_CLI LIKE 'J%'




