--COMANDO PARA DROPAR O BANCO
DROP DATABASE academico;

--COMANDO QUE CRIA O BANCO DE DADOS
CREATE DATABASE PET_SHOP_2B;

--COMANDO PARA USAR O BANCO
USE PET_SHOP_2B;

--CRIAR TABELA NO BANCO
CREATE TABLE RACA(
  ID_RACA INT PRIMARY KEY IDENTITY(1,1),
  NOME_RACA VARCHAR (100) NOT NULL);

  --INSERINDO VALOR NA TABELA/COMANDOS PARA INSERIR
  --EXEMPLOS - PROF
  INSERT INTO RACA(NOME_RACA) VALUES ('PASTOR ALEMÃO');
  INSERT INTO RACA(NOME_RACA) VALUES ('YORKSHIRE');
  --EXEMPLOS - EDUTY
  INSERT INTO RACA(NOME_RACA) VALUES ('BULDOG');
  INSERT INTO RACA(NOME_RACA) VALUES ('POODLE');
  INSERT INTO RACA(NOME_RACA) VALUES ('PUG');
  INSERT INTO RACA(NOME_RACA) VALUES ('HUSKY SIBERIANO');

  CREATE TABLE ANIMAL(
  ID_ANIMAL INT PRIMARY KEY IDENTITY(1,1),
  NOME_ANIMAL VARCHAR(100) NOT NULL,
  DT_NASC DATETIME NULL,
  PORTE VARCHAR (50),
  SEXO_ANIMAL CHAR(1),
  ID_RACA_FK INT,
  FOREIGN KEY(ID_RACA_FK)
  REFERENCES RACA(ID_RACA))

  INSERT INTO ANIMAL
  VALUES('REXONA', GETDATE(),'PEQUENO', 'M', 2);
  INSERT INTO ANIMAL
  VALUES('TICO TICO', GETDATE(),'MÉDIO', 'M', 4);
  INSERT INTO ANIMAL
  VALUES('LEOZIN', GETDATE(),'GRANDE', 'F', 3);
  
  SELECT * FROM ANIMAL;

  --PESQUISA NA TABELA; SELECIONA OS DADOS/SELECIONA TODOS OS CAMPOS
  SELECT * FROM RACA
  WHERE ID_RACA = 2;
  --PESQUISA CAMPO INDIVIDUAL
  SELECT ID_RACA, NOME_RACA FROM RACA
  WHERE ID_RACA = 2;

  --EXCLUI A TABELA INTEIRA
  DROP TABLE RACA;
  DROP TABLE ANIMAL;
  --DELETAR DADOS
  DELETE FROM RACA;