--COMANDO PARA DROPAR O BANCO
DROP DATABASE academico;

--COMANDO QUE CRIA O BANCO DE DADOS
CREATE DATABASE PET_SHOP_2B;

--COMANDO PARA USAR O BANCO
USE PET_SHOP_2B;

--CRIAR TABELA NO BANCO
CREATE TABLE RACA(
  ID_RACA INT PRIMARY KEY IDENTITY(1,1),
  NOME_RACA VARCHAR (100) NOT NULL);

  --INSERINDO VALOR NA TABELA/COMANDOS PARA INSERIR
  --EXEMPLOS - PROF
  INSERT INTO RACA(NOME_RACA) VALUES ('PASTOR ALEMÃO');
  INSERT INTO RACA(NOME_RACA) VALUES ('YORKSHIRE');
  --EXEMPLOS - EDUTY
  INSERT INTO RACA(NOME_RACA) VALUES ('BULDOG');
  INSERT INTO RACA(NOME_RACA) VALUES ('POODLE');
  INSERT INTO RACA(NOME_RACA) VALUES ('PUG');
  INSERT INTO RACA(NOME_RACA) VALUES ('HUSKY SIBERIANO');
  INSERT INTO RACA(NOME_RACA) VALUES ('DALMATA');
  INSERT INTO RACA(NOME_RACA) VALUES ('PINSCHER');
  INSERT INTO RACA(NOME_RACA) VALUES ('GOLDEN');

  CREATE TABLE ANIMAL(
  ID_ANIMAL INT PRIMARY KEY IDENTITY(1,1),
  NOME_ANIMAL VARCHAR(100) NOT NULL,
  DT_NASC DATETIME NULL,
  PORTE VARCHAR (50),
  SEXO_ANIMAL CHAR(1),
  ID_RACA_FK INT,
  FOREIGN KEY(ID_RACA_FK)
  REFERENCES RACA(ID_RACA))

  INSERT INTO ANIMAL
  VALUES('REXONA', GETDATE(),'PEQUENO', 'M', 2);
  INSERT INTO ANIMAL
  VALUES('TICO TICO', GETDATE(),'MÉDIO', 'M', 4);
  INSERT INTO ANIMAL
  VALUES('LEOZIN', GETDATE(),'GRANDE', 'F', 3);
  INSERT INTO ANIMAL
  VALUES('RENAN', GETDATE(),'MÉDIO', 'F', 8);
  INSERT INTO ANIMAL
  VALUES('TOTTO', GETDATE(),'PEQUENO', 'M', 9);
  INSERT INTO ANIMAL
  VALUES('DIMDIM', GETDATE(),'PEQUENO', 'M', 9);
  INSERT INTO ANIMAL
  VALUES('LILI', GETDATE(),'PEQUENO', 'F', 9);
  
  SELECT * FROM ANIMAL;

    --DELETAR UMA LINHA DA TABELA
  DELETE FROM ANIMAL 
  WHERE ID_ANIMAL = 5;

  --PESQUISA NA TABELA; SELECIONA OS DADOS/SELECIONA TODOS OS CAMPOS
  SELECT * FROM RACA

   --PESQUISA CAMPO INDIVIDUAL
  WHERE ID_RACA = 2;

  --PESQUISA VARIOS CAMPOS ESPECIFICOS, VC PODE ESCOLHER
  SELECT ID_RACA, NOME_RACA FROM RACA
  WHERE ID_RACA = 2;

  --EXCLUI A TABELA INTEIRA
  DROP TABLE RACA;
  DROP TABLE ANIMAL;
  --DELETAR DADOS
  DELETE FROM RACA;



  --EXERCICIO CRIAR UMA TABELA DE CLIENTES
  --CLIENTES

 CREATE TABLE CLIENTE(
  ID_CLI INT PRIMARY KEY IDENTITY(1,1),
  NOME_CLI VARCHAR (100) NOT NULL,
  SEXO_CLI CHAR(1),
  CPF INT NOT NULL,
  EMAIL VARCHAR (50) NOT NULL,
  DATA_NASC DATETIME NOT NULL);

  --EXERCICIO 2 - INSERIR DADOS DO CLIENTE

  INSERT INTO CLIENTE
  VALUES('007 - KAUA', 'M', '541.886.496-09', 'RM08426@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('CALVO AOS 17 - ISAAC', 'M', '414.893.012-39', 'RM48159@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('MANO LEO',  'M', '057.535.021-02', 'RM08424@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('CAIO PAI DE FML', 'F', '145.414.256-99', 'RM48084@ESTUDANTE.FIEB.EDU.BR', GETDATE());
