--COMANDO PARA DROPAR O BANCO
DROP DATABASE academico;

--COMANDO QUE CRIA O BANCO DE DADOS
CREATE DATABASE PET_SHOP_2B;

--COMANDO PARA USAR O BANCO
USE PET_SHOP_2B;

--CRIAR TABELA NO BANCO
CREATE TABLE RACA(
  ID_RACA INT PRIMARY KEY IDENTITY(1,1),
  NOME_RACA VARCHAR (100) NOT NULL);

  --INSERINDO VALOR NA TABELA/COMANDOS PARA INSERIR
  --EXEMPLOS - PROF
  INSERT INTO RACA(NOME_RACA) VALUES ('PASTOR ALEMÃO');
  INSERT INTO RACA(NOME_RACA) VALUES ('YORKSHIRE');
  --EXEMPLOS - EDUTY
  INSERT INTO RACA(NOME_RACA) VALUES ('BULDOG');
  INSERT INTO RACA(NOME_RACA) VALUES ('POODLE');
  INSERT INTO RACA(NOME_RACA) VALUES ('PUG');
  INSERT INTO RACA(NOME_RACA) VALUES ('HUSKY SIBERIANO');
  INSERT INTO RACA(NOME_RACA) VALUES ('DALMATA');
  INSERT INTO RACA(NOME_RACA) VALUES ('PINSCHER');
  INSERT INTO RACA(NOME_RACA) VALUES ('GOLDEN');

  CREATE TABLE ANIMAL(
  ID_ANIMAL INT PRIMARY KEY IDENTITY(1,1),
  NOME_ANIMAL VARCHAR(100) NOT NULL,
  DT_NASC DATETIME NULL,
  PORTE VARCHAR (50),
  SEXO_ANIMAL CHAR(1),
  ID_RACA_FK INT,
  FOREIGN KEY(ID_RACA_FK)
  REFERENCES RACA(ID_RACA))

  INSERT INTO ANIMAL
  VALUES('REXONA', GETDATE(),'PEQUENO', 'M', 2);
  INSERT INTO ANIMAL
  VALUES('TICO TICO', GETDATE(),'MÉDIO', 'M', 4);
  INSERT INTO ANIMAL
  VALUES('LEOZIN', GETDATE(),'GRANDE', 'F', 3);
  INSERT INTO ANIMAL
  VALUES('RENAN', GETDATE(),'MÉDIO', 'F', 8);
  INSERT INTO ANIMAL
  VALUES('TOTTO', GETDATE(),'PEQUENO', 'M', 9);
  INSERT INTO ANIMAL
  VALUES('DIMDIM', GETDATE(),'PEQUENO', 'M', 9);
  INSERT INTO ANIMAL
  VALUES('LILI', GETDATE(),'PEQUENO', 'F', 9);
  
  SELECT * FROM ANIMAL;

    --DELETAR UMA LINHA DA TABELA
  DELETE FROM ANIMAL 
  WHERE ID_ANIMAL = 5;

  --PESQUISA NA TABELA; SELECIONA OS DADOS/SELECIONA TODOS OS CAMPOS
  SELECT * FROM RACA

   --PESQUISA CAMPO INDIVIDUAL
  WHERE ID_RACA = 2;

  --PESQUISA VARIOS CAMPOS ESPECIFICOS, VC PODE ESCOLHER
  SELECT ID_RACA, NOME_RACA FROM RACA
  WHERE ID_RACA = 2;

  --EXCLUI A TABELA INTEIRA
  DROP TABLE RACA;
  DROP TABLE ANIMAL;
  --DELETAR DADOS
  DELETE FROM RACA;



  --EXERCICIO CRIAR UMA TABELA DE CLIENTES
  --CLIENTES

 CREATE TABLE CLIENTE(
  ID_CLI INT PRIMARY KEY IDENTITY(1,1),
  NOME_CLI VARCHAR (100) NOT NULL,
  SEXO_CLI CHAR(1),
  CPF INT NOT NULL,
  EMAIL VARCHAR (50) NOT NULL,
  DATA_NASC DATETIME NOT NULL);

  --EXERCICIO 2 - INSERIR DADOS DO CLIENTE

  INSERT INTO CLIENTE
  VALUES('007 - KAUA', 'M', '541.886.496-09', 'RM08426@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('CALVO AOS 17 - ISAAC', 'M', '414.893.012-39', 'RM48159@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('MANO LEO',  'M', '057.535.021-02', 'RM08424@ESTUDANTE.FIEB.EDU.BR', GETDATE());
  INSERT INTO CLIENTE
  VALUES('CAIO PAI DE FML', 'F', '145.414.256-99', 'RM48084@ESTUDANTE.FIEB.EDU.BR', GETDATE());


  --23/05/2022 - Exercício: Criar uma tabela Funcionários

  CREATE TABLE FUNCIONARIO(
  ID_FUNC INT PRIMARY KEY IDENTITY(1,1),
  NOME_FUNC VARCHAR (100) NOT NULL,
  DT_NASC_FUNC DATE NOT NULL,
  TEL_FUNC VARCHAR (30) NOT NULL,
  SEXO_FUNC CHAR(1),
  EMAIL_FUNC VARCHAR (100),
  CPF_FUNC VARCHAR (20));
  
  INSERT INTO FUNCIONARIO
  VALUES('Leonardo Alvarez', '16/03/2005', '11 934327472', 'M', 'manoleo@func.itau.com', '654.789.285-34');

  INSERT INTO FUNCIONARIO
  VALUES('Renan Thiago da Silva', '10/07/2006', '11 964680873', 'M', 'renanzin@func.itau.com', '845.149.072-08');

  INSERT INTO FUNCIONARIO
  VALUES('Grazyelli Ramos', '09/10/2005', '11 973550835', 'F', 'grazy@func.itau.com', '086.374.716-94');
  
  INSERT INTO FUNCIONARIO
  VALUES('Kennedy Gabriel Andrade', '29/06/2004', '11 916541177', 'M', 'kenedito@func.itau.com', '031.733.325-67');

  INSERT INTO FUNCIONARIO
  VALUES('Kaua Florencio', '09/11/2005', '11 9764810297', 'M', '007@func.itau.com', '194.417.252-19');

  INSERT INTO FUNCIONARIO
  VALUES('Gabrielli Senegali Cristianini', '18/01/2006', '11 971871064', 'F', 'gabi@func.itau.com', '715.097.037-71');

  INSERT INTO FUNCIONARIO
  VALUES('Caio Dantas Cordeiro', '30/12/2004', '11 974169428', 'M', 'paifml@func.itau.com', '107.671.037-88');

  INSERT INTO FUNCIONARIO
  VALUES('Sabrina Sena Chiozzotto', '11/08/2003', '11 907873849', 'F', 'SahChio@func.itau.com', '123.456.789-00');

  INSERT INTO FUNCIONARIO
  VALUES('Breno Maximo Balduino', '15/04/2005', '11 915796418', 'M', 'brenao@func.itau.com', '478.014.675-44');

  INSERT INTO FUNCIONARIO
  VALUES('Victoria Soares Damasceno', '12/03/2005', '11 904786412', 'F', 'VicDamas@func.itau.com', '145.176.348-25');

  SELECT * FROM FUNCIONARIO

  DROP TABLE FUNIONARIO