--REVISÃO PARA PROVA TRI
use SUPERMERCADO_2B

--ALTERAR TELEFONE
UPDATE FORNECEDOR
SET TELEFONE = '1155553894',
EMAIL_FORN = 'DUTYS@GMAIL.COM.BR'
WHERE COD_FORN = 1005

select * from FORNECEDOR
WHERE COD_FORN = 1005

select * from PRODUTO
WHERE NOME_PROD LIKE '%COND%'

select * from PRODUTO
ORDER BY NOME_PROD DESC

select * from PRODUTO
ORDER BY NOME_PROD ASC

select * from PRODUTO
ORDER BY COD_PROD ASC